### ISSUE TITLE
`scale` with scalar factor fails: "some fields set to invalid numbers"

### ISSUE THREAD

**Issue by mccalluc** [uber-web/math.gl#40]
From the docs:
> Adds a scaling transform, each axis can be scaled independently.
> matrix4.scale(factor)
>  factor (Number) - scale factor to be applied to each axis.

But for me, while a three element array works, giving it a single scalar does not.
```
import {Matrix4} from 'math.gl';

describe('Matrix4', ()=>{
  function withArray() {
    return new Matrix4().scale([2,2,2]);
  }
  function withScalar() {
    return new Matrix4().scale(2);
  }
  it('scales with array', ()=>{
    withArray();
  });
  it('scales with scalar', ()=>{
    withScalar();
  });
  it('and they mean the same thing', ()=>{
    expect(withArray().toString()).toEqual(withScalar().toString());
  });
});
```
`scales with array` passes, but the other two error:
```
math.gl: Matrix4 some fields set to invalid numbers'
...
      at Array.check (node_modules/math.gl/src/lib/math-array.js:158:13)
      at Array.check (node_modules/math.gl/src/matrix4.js:339:17)
      at scale (src/matrix.test.js:8:26)
      at Object.withScalar (src/matrix.test.js:17:44)
```

**Comment by ibgreen** [comment]
@XiaokaiUber Let's publish a patch release to unblock users.
